#!/usr/bin/bash

function backup_tar() {
  rute=`dirname -- $(realpath ${BASH_SOURCE[0]})`
  . $rute/lib/create
  . $rute/lib/reply

  target=`parse-input "$1"`

  is_archive? "$1"
  case $? in
    "0")
      archive="$1"
      ;;
    *)
      [[ -z "$1" ]] && reply -e "Please specify a target:\n  backup <file|archive.xz>"
      is_file? "$1" && target="$1" || reply -e "File not found: $1"
      ;;
  esac

  ## Ensure BAK_DIR ends with a single '/' if it exists
  if [[ -n $BAK_DIR ]]
  then [[ $BAK_DIR =~ /$ ]] || export BAK_DIR=$BAK_DIR/
  fi

  leaf=`echo ${target:-$archive}     | awk -F'/' '{print $NF}'`
  path=`realpath ${target:-$archive} | sed -e "s/\/${leaf}//g"`
  archive=${archive:-"${BAK_DIR:-$path/.}${target%.[a-z]*}.txz"}
  now=`date -u +%s`
  WRK=`mktemp -d`

  create_tar

  # Cleanup
  rm -rf $WRK
  unset archive leaf now path WRK
}

backup_tar "$@"
