#!/usr/bin/bash

function backup_tar() {
  rute=`dirname -- $(realpath ${BASH_SOURCE[0]})`
  . $rute/lib/create
  . $rute/lib/reply

  target=`parse-input "$1"`
  [ $? -eq 1 ] && reply -e "Target file/directory not found: $1"

  ## Ensure BAK_DIR ends with a single '/' if it exists
  if [[ -n $BAK_DIR ]]
  then [[ $BAK_DIR =~ /$ ]] || export BAK_DIR=$BAK_DIR/
  fi

  leaf=`echo $target | awk -F'/' '{print $NF}'`
  path=`echo $target | sed -e "s/\/${leaf}//g"`
  archive="${BAK_DIR:-$path/.}${leaf%.[a-z]*}.txz"
  WRK=`mktemp -d`

  create_tar

  # Cleanup
  rm -rf $WRK
  unset archive leaf path target WRK
}

backup_tar "$@"
