#!/usr/bin/bash

. $here/lib/checks
. $here/lib/sums

function create_tar() {
  is_archive? "${path}/${archive}"
  case $? in 
    "0")
      . lib/append

      append_tar
      ;;
    *)
      is_file? "${path}/${archive}" && ( mv -v "${path}/${archive}" "${path}/${archive}.old" )

      tmp_path=`compress-sum "$path/$leaf" "$WRK" | awk '{print $NF}' | sed "s/'//g"`
      tmp_leaf=`echo $tmp_path | awk -F'/' '{print $NF}' | sed "s/'//g"`

      tar cJf "${path}/${archive}" -C "${tmp_path%/$tmp_leaf}" "$tmp_leaf"
      ;;
  esac
}
