#!/usr/bin/env bash

function rn-sum() {
  dest="${2:-.}"
  sum=`md5sum "$1" | awk '{print $1}'`

  mv -v "$1" "$dest/$sum"
}

function compress-sum() {
  leaf=`echo $1 | awk -F'/' '{print $NF}'`
  archive="${leaf}.txz"
  dest="${2:-.}"
  src="${1%$leaf}"

  tar cJf "$dest/$archive" -C "$src" "$leaf"
  rn-sum "$dest/$archive" "$dest"
}

function unique-sums() {
  car="$1"
  sum="$2"
  list=(`tar tif "$car"`)

  [[ "${list[@]}" =~ "$sum" ]] && return 1 || return 0
}
